### ISSUE TITLE
3 engines detected this file

### ISSUE THREAD

**Issue by Feuerkl1nge** [szapp/Ninja#24]
virustotal.com
Regarding v2.3+ 
What's up with that file?
![firefox_H3DX7uCLwb](https://user-images.githubusercontent.com/64936130/107127421-4ec80500-68b6-11eb-9747-3fae33c1b7ef.png)

**Comment by szapp** [comment]
It is a false positive. These are unfortunately very common for setups of Nullsoft Scriptable Install System. It is a [known issue](https://nsis.sourceforge.io/NSIS_False_Positives).

You can verify your setup with the provided [checksums](../wiki/Checksums#wiki-wrapper).
