### ISSUE TITLE
Text currently printed with PrintS_Ext sometimes is stuck on reloading the game

### ISSUE THREAD

**Issue by Avenire** [szapp/Ninja#32]
Hi, thanks for your work and recent updates!

I recently noticed that in my whacky plugin, if I reload the game shortly after I printed a text notification to the screen using `PrintS_Ext`, the message gets permanently stuck on the screen until I restart the game. I've managed to reproduce this in both Gothic 1 and Gothic 2 NotR, both with Ninja and the latest Union installed (via Steam workshop). 

I tried downgrading to Ninja 2.7.12 - couldn't reproduce the issue then. 
Did another test, snatched the original Lego's `PrintS_Ext` implementation into my project, on each call saved a raw pointer to `zCTextView` object saved in `gCPrintS::tv_Text`. Then, on the next init run after reloading, I manually called `zCTextView_Delete` with each saved ptr (which should have been done as part of  `_PM_Reset()` cleanup as far as I understood Lego source code). I couldn't reproduce the issue then neither so seems like something may be off with PermMem handles cleanup? 

I made a minimum repro-plugin here https://github.com/Avenire/ninjapermmemhandleleak
Steps to reproduce is just smash V button 15+ times & quickly reload the game while text is still on the screen. 
Also, recorded my reproduction attempts, looks like the bug was introduced with 2.8.13:
Ninja 2.7.12 - no bug: https://youtu.be/bOEN2DFBoh4
Ninja 2.8.13 - bugged: https://youtu.be/tOt4FWtrw_M
Ninja 2.9.14 - bugged: https://youtu.be/a3gmqPQSrec

**Comment by szapp** [comment]
Thank you for the amazing and thorough bug report! Thanks for using the template; with the familiar file structure I could immediately understand what that patch is doing. 

I am surprised that issue popped up just now and is not present with previous Ninja versions. I'd also like to pinpoint whether that is an issue with PermMem (i.e. LeGo) in general or specifically with the patch-specific version supplied in Ninja. 

I hope to find some time on the weekend to investigate. Would you be willing to assist in testing any potential fixes?

**Comment by Avenire** [comment]
Yeah sure, no hurry 😊. I can help with testing.

**Comment by szapp** [comment]
Just to keep it transparent and to keep you updated. I have a hunch. In v2.8.13, I did an overhaul of how PermMem handles (of patches) are saved to greatly improve performance (from up to tens of seconds to one-digit milliseconds!). Much like the hotfix of v2.9.14, I might have made another mistake: If the underlying mod does not use PermMem, patch handles are not correctly reset.

I will do my best to test it myself, of course. But is there a way to contact you privately to send you a development version of Ninja? I wouldn't like to post it publicly.

**Comment by Avenire** [comment]
Thanks. I've enabled my email visibility in the profile page, feel free to use it.

**Comment by szapp** [comment]
I dug a little deeper and the origin of the bug was actually in LeGo. Changes in the handle iteration skipped some handles during resetting. Yet, I am not denying responsibility: The [respective changes](https://github.com/Lehona/LeGo/commit/97e5e4f5929d8fddae9ce0f056497ba6d6780c70) were authored by me. I will shortly push a fix to LeGo and Avenire and I will test the changes for a bit until there is an update of Ninja.

@Avenire Thanks! I noted down your contact. Feel free to change the email visibility again if you prefer. I will send you a test version later this weekend!

**Comment by szapp** [comment]
@Avenire I sent you a test version, but my first email got rejected. Would you briefly confirm that you received my second email?

**Comment by Avenire** [comment]
@szapp got it, thanks

**Comment by Avenire** [comment]
I didn't have much time to test it last weekend but I couldn't reproduce the original issue with my repro-plugin in G1. Looking good so far.

**Comment by szapp** [comment]
@Avenire thanks a lot! I will close the issue as resolved for now, but will hold of with a new version for a bit longer. There was another problem reported elsewhere, but it's not clear whether that's a bug or user error.

Feel free to reopen/discuss the issue further should there be more problems.
